name: Setup Node and pnpm
description: Setup Node, activate Corepack pnpm, install dependencies

inputs:
  node-version:
    description: Node.js version
    required: false
    default: "26.x"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Enable corepack and install pnpm
      shell: bash
      run: |
        corepack enable
        corepack prepare pnpm@11.5.0+sha512.dbfcc4f81cf48597afd4bc391ffdf12c11f1a9fb83a395bfa6b0a2d9cc2fd8ffebafdb1ccbd529632153f793904c2615b7f09fe1a345473fd1c35845172a8eb1 --activate
        pnpm --version

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
