import { debugError, debugLog } from "@/lib/debug";

// app/api/reports/generate/route.ts
import { auth } from '@/lib/auth';
import { db } from '@/lib/db';
import { profiles } from '@/lib/db/schema';
import { eq } from 'drizzle-orm';
import fs from 'fs';
import { NextResponse } from 'next/server';
import path from 'path';

// ============================================================================
// REPORT GENERATION API - Pro User Document Download
// ============================================================================
// This route handles:
// 1. User authentication and Pro plan validation
// 2. Credit deduction (server-side)
// 3. File generation in multiple formats (pdf, ppt, docx, xlsx)
// 4. Temporary file storage in the app assets directory (served at /assets/generated/)
// ============================================================================

function getGeneratedAssetsDir() {
  if (process.env.NODE_ENV === 'production') {
    return path.join(process.cwd(), 'assets', 'generated')
  }

  return path.join(process.cwd(), 'src', 'assets', 'generated')
}

/**
 * Generate a simple text-based report file
 * Minimal version - generates basic files for each format
 */
async function generateReportFile(
  format: string,
  reportData: any,
  fileName: string
): Promise<string> {
  const publicDir = getGeneratedAssetsDir()

  // Ensure directory exists
  if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
  }

  const filePath = path.join(publicDir, fileName);
  let content = '';

  // Generate content based on format
  switch (format) {
    case 'pdf':
      // Simple text-based PDF alternative (actual PDF generation would require a library)
      content = generateTextReport(reportData);
      fs.writeFileSync(filePath.replace('.pdf', '.txt'), content);
      return `/assets/generated/${fileName.replace('.pdf', '.txt')}`;

    case 'ppt':
      // Simple text-based presentation outline
      content = generatePptOutline(reportData);
      fs.writeFileSync(filePath.replace('.ppt', '.txt'), content);
      return `/assets/generated/${fileName.replace('.ppt', '.txt')}`;

    case 'docx':
      // Simple text-based Word document
      content = generateDocContent(reportData);
      fs.writeFileSync(filePath.replace('.docx', '.txt'), content);
      return `/assets/generated/${fileName.replace('.docx', '.txt')}`;

    case 'xlsx':
      // Simple CSV-based Excel alternative
      content = generateCsvData(reportData);
      fs.writeFileSync(filePath.replace('.xlsx', '.csv'), content);
      return `/assets/generated/${fileName.replace('.xlsx', '.csv')}`;

    default:
      throw new Error(`Unsupported format: ${format}`);
  }
}

/**
 * Generate text-based report content
 */
function generateTextReport(data: any): string {
  const lines = [
    '========================================',
    data.title || 'Executive Report',
    '========================================',
    '',
    'EXECUTIVE SUMMARY',
    '----------------------------------------',
    data.executive_summary || 'No summary available.',
    '',
    'KEY PERFORMANCE INDICATORS',
    '----------------------------------------',
  ];

  if (data.kpis && Array.isArray(data.kpis)) {
    data.kpis.forEach((kpi: any, index: number) => {
      lines.push(`${index + 1}. ${kpi.name}: ${kpi.value}`);
      lines.push(`   Insight: ${kpi.insight}`);
      lines.push('');
    });
  }

  lines.push('');
  lines.push('SECTIONS');
  lines.push('----------------------------------------');

  if (data.sections && Array.isArray(data.sections)) {
    data.sections.forEach((section: any, index: number) => {
      lines.push(`${index + 1}. ${section.title}`);
      lines.push(`   ${section.content}`);
      lines.push('');
    });
  }

  lines.push('');
  lines.push('========================================');
  lines.push('Generated by UseClevr');
  lines.push(`Date: ${new Date().toISOString()}`);

  return lines.join('\n');
}

/**
 * Generate PPT outline content
 */
function generatePptOutline(data: any): string {
  const lines = [
    'PRESENTATION OUTLINE',
    '==================',
    '',
    `Title: ${data.title || 'Executive Presentation'}`,
    '',
    'SLIDES:',
    '',
    '1. Executive Summary',
    `   ${data.executive_summary || 'Overview of the report'}`,
    '',
  ];

  if (data.kpis && Array.isArray(data.kpis)) {
    lines.push('2. Key Performance Indicators');
    data.kpis.forEach((kpi: any) => {
      lines.push(`   - ${kpi.name}: ${kpi.value}`);
    });
    lines.push('');
  }

  if (data.sections && Array.isArray(data.sections)) {
    data.sections.forEach((section: any, index: number) => {
      lines.push(`${(data.kpis ? 3 : 2) + index}. ${section.title}`);
      lines.push(`   ${section.content?.substring(0, 100)}...`);
      lines.push('');
    });
  }

  return lines.join('\n');
}

/**
 * Generate DOC content
 */
function generateDocContent(data: any): string {
  const lines = [
    data.title || 'Executive Report',
    '='.repeat(50),
    '',
    'EXECUTIVE SUMMARY',
    '',
    data.executive_summary || 'No summary available.',
    '',
    'KEY PERFORMANCE INDICATORS',
    '',
  ];

  if (data.kpis && Array.isArray(data.kpis)) {
    data.kpis.forEach((kpi: any) => {
      lines.push(`• ${kpi.name}: ${kpi.value}`);
      lines.push(`  ${kpi.insight}`);
      lines.push('');
    });
  }

  return lines.join('\n');
}

/**
 * Generate CSV data for Excel
 */
function generateCsvData(data: any): string {
  const lines: string[] = [];

  // KPIs as CSV
  lines.push('KEY PERFORMANCE INDICATORS');
  lines.push('Name,Value,Insight');

  if (data.kpis && Array.isArray(data.kpis)) {
    data.kpis.forEach((kpi: any) => {
      lines.push(`"${kpi.name}","${kpi.value}","${kpi.insight}"`);
    });
  }

  lines.push('');
  lines.push('SECTIONS');
  lines.push('Title,Content');

  if (data.sections && Array.isArray(data.sections)) {
    data.sections.forEach((section: any) => {
      lines.push(`"${section.title}","${section.content?.substring(0, 50)}..."`);
    });
  }

  return lines.join('\n');
}

export async function POST(request: Request) {
  try {
    // 1. Authenticate user
    const session = await auth();
    const userId = (session?.user as { id?: string })?.id;

    if (!userId) {
      return NextResponse.json(
        { success: false, error: 'Authentication required' },
        { status: 401 }
      );
    }

    // 2. Parse request body
    const body = await request.json();
    const { format, reportData } = body;

    if (!format || !reportData) {
      return NextResponse.json(
        { success: false, error: 'Missing required fields: format, reportData' },
        { status: 400 }
      );
    }

    // Validate format
    const validFormats = ['pdf', 'ppt', 'docx', 'xlsx'];
    if (!validFormats.includes(format)) {
      return NextResponse.json(
        { success: false, error: `Invalid format. Supported: ${validFormats.join(', ')}` },
        { status: 400 }
      );
    }

    // 3. Fetch user profile
    const profile = await db.query.profiles.findFirst({
      where: eq(profiles.userId, userId),
    });

    if (!profile) {
      return NextResponse.json(
        { success: false, error: 'Profile not found' },
        { status: 404 }
      );
    }

    // 4. Validate Pro plan
    if (profile.subscriptionTier !== 'pro') {
      return NextResponse.json(
        { success: false, error: 'Pro subscription required for report generation' },
        { status: 403 }
      );
    }

    // 5. Validate credits
    if (profile.credits <= 0) {
      return NextResponse.json(
        { success: false, error: 'No credits remaining. Please purchase credits to generate reports.' },
        { status: 403 }
      );
    }

    // 6. Generate unique filename
    const timestamp = Date.now();
    const fileName = `report_${userId}_${timestamp}.${format}`;

    // 7. Generate report file
    const fileUrl = await generateReportFile(format, reportData, fileName);

    // 8. Deduct credit (server-side only)
    await db.update(profiles)
      .set({ credits: profile.credits - 1 })
      .where(eq(profiles.userId, userId));

    debugLog(`[REPORT] Generated ${format} report for user ${userId}, credits remaining: ${profile.credits - 1}`);

    return NextResponse.json({
      success: true,
      fileUrl,
      creditsRemaining: profile.credits - 1,
    });

  } catch (error) {
    debugError('[REPORT ERROR]', error);
    return NextResponse.json(
      { success: false, error: 'Failed to generate report' },
      { status: 500 }
    );
  }
}
