"use client"

import { Button } from "@/components/ui/button"
import {
  AlertTriangle,
  ArrowUpRight,
  BarChart3,
  Brain,
  CheckCircle2,
  CircleDollarSign,
  Download,
  FileSpreadsheet,
  FileText,
  LineChart as LineChartIcon,
  Link as LinkIcon,
  PieChart,
  Presentation,
  Printer,
  ShieldAlert,
  Sparkles,
  Target,
  TrendingUp,
} from "lucide-react"
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  ComposedChart,
  Line,
  Radar,
  RadarChart,
  PolarAngleAxis,
  PolarGrid,
  PolarRadiusAxis,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts"
import { useMemo, useState } from "react"

const report = {
  company: "Northstar Commerce Group",
  period: "FY 2026 sample report",
  generatedAt: "Generated by UseClevr AI from 24 months of sales, finance, inventory, and customer data.",
  healthScore: 82,
  confidenceScore: 94,
  overview:
    "Northstar Commerce Group shows strong revenue momentum, improving customer acquisition, and healthy category expansion. The AI analysis identifies margin pressure in wholesale channels, inventory concentration in slow-moving SKUs, and a clear revenue upside in premium bundles and the Northeast region.",
}

const kpis = [
  { label: "Revenue", value: "$4.82M", change: "+18.4%", tone: "cyan", detail: "Trailing 12 months" },
  { label: "Gross Profit", value: "$1.71M", change: "+14.1%", tone: "purple", detail: "35.5% gross margin" },
  { label: "Net Margin", value: "12.8%", change: "+2.1 pts", tone: "cyan", detail: "After fixed costs" },
  { label: "Growth Rate", value: "21.6%", change: "+5.7 pts", tone: "purple", detail: "Year over year" },
  { label: "Inventory Health", value: "76/100", change: "+9", tone: "cyan", detail: "Reorder risk improving" },
  { label: "Customer Growth", value: "+24.3%", change: "+1,840", tone: "purple", detail: "New accounts" },
]

const revenueTrend = [
  { month: "Jan", revenue: 310, profit: 96, forecast: 324 },
  { month: "Feb", revenue: 326, profit: 103, forecast: 336 },
  { month: "Mar", revenue: 342, profit: 109, forecast: 351 },
  { month: "Apr", revenue: 338, profit: 104, forecast: 358 },
  { month: "May", revenue: 371, profit: 118, forecast: 374 },
  { month: "Jun", revenue: 394, profit: 127, forecast: 402 },
  { month: "Jul", revenue: 418, profit: 139, forecast: 426 },
  { month: "Aug", revenue: 436, profit: 145, forecast: 444 },
  { month: "Sep", revenue: 459, profit: 151, forecast: 468 },
  { month: "Oct", revenue: 482, profit: 162, forecast: 491 },
  { month: "Nov", revenue: 506, profit: 171, forecast: 516 },
  { month: "Dec", revenue: 548, profit: 188, forecast: 552 },
]

const categoryPerformance = [
  { name: "Premium", revenue: 1420, margin: 42 },
  { name: "Core", revenue: 1180, margin: 34 },
  { name: "Bundles", revenue: 820, margin: 39 },
  { name: "Wholesale", revenue: 760, margin: 24 },
  { name: "Clearance", revenue: 360, margin: 16 },
]

const monthlyComparison = [
  { month: "Q1", current: 978, previous: 842 },
  { month: "Q2", current: 1103, previous: 921 },
  { month: "Q3", current: 1313, previous: 1068 },
  { month: "Q4", current: 1536, previous: 1290 },
]

const regionalPerformance = [
  { region: "Northeast", score: 92, revenue: 1220 },
  { region: "West", score: 86, revenue: 1080 },
  { region: "South", score: 78, revenue: 910 },
  { region: "Midwest", score: 74, revenue: 830 },
  { region: "Online", score: 89, revenue: 1180 },
]

const heatmap = [
  ["Premium", "Northeast", "High", "$310K"],
  ["Bundles", "Online", "High", "$270K"],
  ["Core", "West", "Medium", "$145K"],
  ["Wholesale", "South", "Medium", "$92K"],
  ["Clearance", "Midwest", "Low", "$38K"],
]

const findings = [
  {
    title: "Opportunities discovered",
    icon: Target,
    items: ["Premium bundles outperform standalone SKUs by 17%.", "Northeast demand increased for four consecutive months.", "Online repeat orders show the highest customer lifetime value."],
  },
  {
    title: "Risks detected",
    icon: ShieldAlert,
    items: ["Wholesale margin fell below target in Q4.", "Slow-moving inventory ties up $186K of working capital.", "Three regions depend on one top customer segment."],
  },
  {
    title: "Performance anomalies",
    icon: AlertTriangle,
    items: ["October discounting lifted sales but reduced margin quality.", "Accessory sales rose despite lower campaign spend.", "Returns increased in two clearance categories."],
  },
  {
    title: "Forecast highlights",
    icon: LineChartIcon,
    items: ["Expected next-quarter revenue range: $1.42M-$1.51M.", "Gross margin recovers if wholesale discounting is reduced.", "Inventory turns improve with targeted SKU rebalancing."],
  },
]

const recommendations = [
  {
    title: "Shift acquisition budget toward premium bundles",
    priority: "High",
    impact: "$280K-$340K revenue upside",
    effort: "Medium",
    reasoning: "Bundle conversion is 22% higher than standalone offers, and repeat purchase rates are strongest in the same customer cohort.",
  },
  {
    title: "Reduce wholesale discount leakage",
    priority: "High",
    impact: "+3.4 pts gross margin",
    effort: "Low",
    reasoning: "Wholesale revenue grew, but discount depth outpaced volume gains. Repricing the bottom quartile protects profit without reducing top accounts.",
  },
  {
    title: "Rebalance inventory across five slow-moving SKU families",
    priority: "Medium",
    impact: "$120K working-capital release",
    effort: "Medium",
    reasoning: "Inventory aging is concentrated in a narrow set of categories with declining sell-through and weak regional demand.",
  },
  {
    title: "Launch Northeast customer expansion playbook",
    priority: "Medium",
    impact: "+9%-12% regional growth",
    effort: "Low",
    reasoning: "The region combines high margin, accelerating demand, and low churn, making it the clearest near-term expansion target.",
  },
]

const risks = [
  { type: "Financial", status: "Medium", detail: "Margin volatility in wholesale and clearance channels requires tighter pricing control." },
  { type: "Sales", status: "Low", detail: "Pipeline coverage is healthy, but enterprise order timing creates quarterly concentration." },
  { type: "Inventory", status: "High", detail: "Aging stock and regional stockouts coexist, indicating allocation imbalance." },
  { type: "Operational", status: "Medium", detail: "Fulfillment cost per order rose 8.2% as order mix shifted toward lower basket sizes." },
]

const opportunities = [
  { title: "Revenue opportunities", value: "$430K", detail: "Premium bundles, regional expansion, and repeat-order campaigns." },
  { title: "Cost reduction", value: "$96K", detail: "Fulfillment batching and slow-moving SKU markdown governance." },
  { title: "Margin improvements", value: "+4.1 pts", detail: "Wholesale repricing and campaign-level contribution tracking." },
  { title: "Inventory optimization", value: "$186K", detail: "Working capital tied to low-velocity categories." },
  { title: "Customer growth", value: "+2.8K", detail: "Lookalike acquisition from high-LTV segments." },
]

const chartTabs = [
  "Revenue trend",
  "Profit trend",
  "Category performance",
  "Monthly comparison",
  "Regional performance",
  "Opportunity heatmap",
] as const

type ChartTab = (typeof chartTabs)[number]

type TooltipPayload = {
  name?: string
  value?: number | string
  color?: string
}

type DemoTooltipProps = {
  active?: boolean
  label?: string
  payload?: TooltipPayload[]
}

function DemoTooltip({ active, label, payload }: DemoTooltipProps) {
  if (!active || !payload?.length) return null

  return (
    <div className="rounded-lg border border-white/10 bg-slate-950/95 px-3 py-2 text-xs text-slate-100 shadow-xl shadow-black/30">
      <p className="mb-1 font-semibold text-white">{label}</p>
      {payload.map((item) => (
        <p key={`${item.name}-${item.value}`} style={{ color: item.color }}>
          {item.name}: {item.value}
        </p>
      ))}
    </div>
  )
}

function ScoreRing({ value, label, color }: { value: number; label: string; color: "cyan" | "purple" }) {
  const stroke = color === "cyan" ? "#22D3EE" : "#A78BFA"
  const circumference = 2 * Math.PI * 42
  const offset = circumference - (value / 100) * circumference

  return (
    <div className="flex items-center gap-4 rounded-lg border border-white/10 bg-white/[0.04] p-4 print:border-slate-200 print:bg-white">
      <svg className="h-24 w-24 shrink-0" viewBox="0 0 100 100" role="img" aria-label={`${label}: ${value} out of 100`}>
        <circle cx="50" cy="50" r="42" fill="none" stroke="rgba(148,163,184,0.18)" strokeWidth="10" />
        <circle
          cx="50"
          cy="50"
          r="42"
          fill="none"
          stroke={stroke}
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          strokeLinecap="round"
          strokeWidth="10"
          transform="rotate(-90 50 50)"
        />
        <text x="50" y="54" fill="currentColor" textAnchor="middle" className="text-xl font-bold">
          {value}
        </text>
      </svg>
      <div>
        <p className="text-sm font-medium text-slate-300 print:text-slate-600">{label}</p>
        <p className="mt-1 text-sm leading-6 text-slate-400 print:text-slate-600">
          {value >= 90 ? "High confidence in detected patterns." : "Strong position with focused improvement areas."}
        </p>
      </div>
    </div>
  )
}

function ChartPanel({ activeTab }: { activeTab: ChartTab }) {
  if (activeTab === "Opportunity heatmap") {
    return (
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
        {heatmap.map(([category, region, priority, value]) => (
          <div
            key={`${category}-${region}`}
            className={[
              "rounded-lg border p-4",
              priority === "High"
                ? "border-cyan-300/30 bg-cyan-300/10"
                : priority === "Medium"
                  ? "border-[#A78BFA]/30 bg-[#7C3AED]/10"
                  : "border-white/10 bg-white/[0.04]",
            ].join(" ")}
          >
            <p className="text-xs uppercase tracking-wide text-slate-400">{priority} opportunity</p>
            <p className="mt-2 text-lg font-semibold text-white print:text-slate-950">{value}</p>
            <p className="mt-1 text-sm text-slate-300 print:text-slate-600">{category}</p>
            <p className="text-xs text-slate-500 print:text-slate-500">{region}</p>
          </div>
        ))}
      </div>
    )
  }

  return (
    <div className="h-[320px]">
      <ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={0}>
        {activeTab === "Revenue trend" ? (
          <AreaChart data={revenueTrend} margin={{ top: 12, right: 20, left: 0, bottom: 8 }}>
            <defs>
              <linearGradient id="sampleRevenue" x1="0" x2="0" y1="0" y2="1">
                <stop offset="0%" stopColor="#22D3EE" stopOpacity={0.42} />
                <stop offset="100%" stopColor="#22D3EE" stopOpacity={0.02} />
              </linearGradient>
            </defs>
            <CartesianGrid stroke="rgba(148,163,184,0.16)" vertical={false} />
            <XAxis dataKey="month" stroke="#94A3B8" tick={{ fontSize: 12 }} />
            <YAxis stroke="#94A3B8" tick={{ fontSize: 12 }} tickFormatter={(value) => `$${value}K`} />
            <Tooltip content={<DemoTooltip />} />
            <Area dataKey="revenue" name="Revenue" type="monotone" stroke="#22D3EE" strokeWidth={3} fill="url(#sampleRevenue)" />
            <Line dataKey="forecast" name="AI forecast" type="monotone" stroke="#A78BFA" strokeDasharray="5 5" strokeWidth={2} dot={false} />
          </AreaChart>
        ) : activeTab === "Profit trend" ? (
          <ComposedChart data={revenueTrend} margin={{ top: 12, right: 20, left: 0, bottom: 8 }}>
            <CartesianGrid stroke="rgba(148,163,184,0.16)" vertical={false} />
            <XAxis dataKey="month" stroke="#94A3B8" tick={{ fontSize: 12 }} />
            <YAxis stroke="#94A3B8" tick={{ fontSize: 12 }} tickFormatter={(value) => `$${value}K`} />
            <Tooltip content={<DemoTooltip />} />
            <Bar dataKey="profit" name="Gross profit" fill="#7C3AED" radius={[5, 5, 0, 0]} />
            <Line dataKey="profit" name="Profit trend" type="monotone" stroke="#22D3EE" strokeWidth={3} />
          </ComposedChart>
        ) : activeTab === "Category performance" ? (
          <ComposedChart data={categoryPerformance} margin={{ top: 12, right: 20, left: 0, bottom: 8 }}>
            <CartesianGrid stroke="rgba(148,163,184,0.16)" vertical={false} />
            <XAxis dataKey="name" stroke="#94A3B8" tick={{ fontSize: 12 }} />
            <YAxis yAxisId="left" stroke="#94A3B8" tick={{ fontSize: 12 }} tickFormatter={(value) => `$${value}K`} />
            <YAxis yAxisId="right" orientation="right" stroke="#94A3B8" tick={{ fontSize: 12 }} tickFormatter={(value) => `${value}%`} />
            <Tooltip content={<DemoTooltip />} />
            <Bar yAxisId="left" dataKey="revenue" name="Revenue" fill="#22D3EE" radius={[5, 5, 0, 0]} />
            <Line yAxisId="right" dataKey="margin" name="Margin" type="monotone" stroke="#A78BFA" strokeWidth={3} />
          </ComposedChart>
        ) : activeTab === "Monthly comparison" ? (
          <BarChart data={monthlyComparison} margin={{ top: 12, right: 20, left: 0, bottom: 8 }}>
            <CartesianGrid stroke="rgba(148,163,184,0.16)" vertical={false} />
            <XAxis dataKey="month" stroke="#94A3B8" tick={{ fontSize: 12 }} />
            <YAxis stroke="#94A3B8" tick={{ fontSize: 12 }} tickFormatter={(value) => `$${value}K`} />
            <Tooltip content={<DemoTooltip />} />
            <Bar dataKey="previous" name="Previous year" fill="#475569" radius={[5, 5, 0, 0]} />
            <Bar dataKey="current" name="Current year" fill="#22D3EE" radius={[5, 5, 0, 0]} />
          </BarChart>
        ) : (
          <RadarChart data={regionalPerformance} margin={{ top: 12, right: 40, left: 40, bottom: 8 }}>
            <PolarGrid stroke="rgba(148,163,184,0.22)" />
            <PolarAngleAxis dataKey="region" tick={{ fill: "#CBD5E1", fontSize: 12 }} />
            <PolarRadiusAxis angle={90} domain={[0, 100]} tick={{ fill: "#94A3B8", fontSize: 10 }} />
            <Tooltip content={<DemoTooltip />} />
            <Radar dataKey="score" name="Regional score" stroke="#22D3EE" fill="#22D3EE" fillOpacity={0.24} />
          </RadarChart>
        )}
      </ResponsiveContainer>
    </div>
  )
}

export function SampleReportExperience() {
  const [activeTab, setActiveTab] = useState<ChartTab>("Revenue trend")
  const [selectedRisk, setSelectedRisk] = useState("Inventory")
  const selectedRiskDetail = useMemo(() => risks.find((risk) => risk.type === selectedRisk) ?? risks[0], [selectedRisk])

  return (
    <div className="bg-slate-950 text-white print:bg-white print:text-slate-950">
      <section className="relative overflow-hidden px-4 py-10 md:px-6 md:py-14 print:px-0 print:py-6">
        <div className="absolute left-1/2 top-0 h-72 w-72 -translate-x-1/2 rounded-full bg-cyan-400/15 blur-3xl print:hidden" />
        <div className="absolute right-0 top-16 h-80 w-80 rounded-full bg-[#7C3AED]/15 blur-3xl print:hidden" />

        <div className="container relative mx-auto max-w-7xl">
          <div className="mb-8 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
            <div className="max-w-3xl">
              <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-cyan-300/25 bg-cyan-300/10 px-4 py-2 text-sm font-medium text-cyan-100 print:border-slate-300 print:bg-white print:text-slate-700">
                <Sparkles className="h-4 w-4 text-[#C4B5FD]" />
                Interactive sample AI business report
              </div>
              <h1 className="text-4xl font-bold tracking-tight md:text-6xl">{report.company}</h1>
              <p className="mt-4 text-lg leading-8 text-slate-300 print:text-slate-700">{report.generatedAt}</p>
            </div>
            <div className="rounded-lg border border-white/10 bg-white/[0.04] p-4 text-sm text-slate-300 print:border-slate-200 print:bg-white print:text-slate-700">
              <p className="font-semibold text-white print:text-slate-950">{report.period}</p>
              <p className="mt-1">Data sources: sales, finance, inventory, CRM</p>
            </div>
          </div>

          <section className="grid gap-4 lg:grid-cols-[0.82fr_1.18fr]">
            <div className="space-y-4">
              <ScoreRing value={report.healthScore} label="Business Health Score" color="cyan" />
              <ScoreRing value={report.confidenceScore} label="AI Confidence Score" color="purple" />
            </div>
            <div className="rounded-lg border border-white/10 bg-white/[0.04] p-6 shadow-2xl shadow-black/20 backdrop-blur print:border-slate-200 print:bg-white print:shadow-none">
              <div className="mb-4 flex items-center gap-3">
                <Brain className="h-5 w-5 text-[#C4B5FD]" />
                <h2 className="text-2xl font-semibold">Executive Summary</h2>
              </div>
              <p className="text-base leading-8 text-slate-300 print:text-slate-700">{report.overview}</p>
              <div className="mt-6 grid gap-3 sm:grid-cols-3">
                {["Growth is strong", "Margin needs focus", "Inventory can improve"].map((item) => (
                  <div key={item} className="rounded-lg border border-white/10 bg-slate-950/45 px-4 py-3 text-sm font-medium text-slate-100 print:border-slate-200 print:bg-slate-50 print:text-slate-800">
                    <CheckCircle2 className="mb-2 h-4 w-4 text-cyan-200 print:text-cyan-700" />
                    {item}
                  </div>
                ))}
              </div>
            </div>
          </section>
        </div>
      </section>

      <main className="container mx-auto max-w-7xl space-y-10 px-4 pb-16 md:px-6 print:px-0">
        <section>
          <div className="mb-4 flex items-center gap-3">
            <BarChart3 className="h-5 w-5 text-cyan-200 print:text-cyan-700" />
            <h2 className="text-2xl font-semibold">KPI Dashboard</h2>
          </div>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {kpis.map((kpi) => (
              <div key={kpi.label} className="rounded-lg border border-white/10 bg-white/[0.04] p-5 print:border-slate-200 print:bg-white">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="text-sm text-slate-400 print:text-slate-600">{kpi.label}</p>
                    <p className="mt-2 text-3xl font-semibold text-white print:text-slate-950">{kpi.value}</p>
                  </div>
                  <span className={["rounded-full px-2.5 py-1 text-xs font-semibold", kpi.tone === "cyan" ? "bg-cyan-300/10 text-cyan-100 print:text-cyan-700" : "bg-[#7C3AED]/15 text-[#DDD6FE] print:text-purple-700"].join(" ")}>
                    {kpi.change}
                  </span>
                </div>
                <p className="mt-4 text-sm text-slate-400 print:text-slate-600">{kpi.detail}</p>
              </div>
            ))}
          </div>
        </section>

        <section>
          <div className="mb-4 flex items-center gap-3">
            <Sparkles className="h-5 w-5 text-[#C4B5FD] print:text-purple-700" />
            <h2 className="text-2xl font-semibold">AI Findings</h2>
          </div>
          <div className="grid gap-4 lg:grid-cols-4">
            {findings.map((finding) => {
              const Icon = finding.icon
              return (
                <div key={finding.title} className="rounded-lg border border-white/10 bg-white/[0.04] p-5 print:border-slate-200 print:bg-white">
                  <Icon className="mb-4 h-6 w-6 text-cyan-200 print:text-cyan-700" />
                  <h3 className="text-lg font-semibold text-white print:text-slate-950">{finding.title}</h3>
                  <div className="mt-4 space-y-3">
                    {finding.items.map((item) => (
                      <p key={item} className="text-sm leading-6 text-slate-300 print:text-slate-700">{item}</p>
                    ))}
                  </div>
                </div>
              )
            })}
          </div>
        </section>

        <section className="rounded-lg border border-white/10 bg-white/[0.04] p-5 print:border-slate-200 print:bg-white">
          <div className="mb-5 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <div className="flex items-center gap-3">
                <PieChart className="h-5 w-5 text-cyan-200 print:text-cyan-700" />
                <h2 className="text-2xl font-semibold">Interactive Charts</h2>
              </div>
              <p className="mt-2 text-sm text-slate-400 print:text-slate-600">Switch views to inspect the same sample dataset from different executive angles.</p>
            </div>
            <div className="flex flex-wrap gap-2 print:hidden">
              {chartTabs.map((tab) => (
                <button
                  key={tab}
                  type="button"
                  onClick={() => setActiveTab(tab)}
                  className={[
                    "rounded-full border px-3 py-1.5 text-xs font-medium transition-colors",
                    activeTab === tab
                      ? "border-cyan-300/40 bg-cyan-300/15 text-cyan-100"
                      : "border-white/10 bg-slate-950/40 text-slate-300 hover:border-[#A78BFA]/40 hover:text-white",
                  ].join(" ")}
                >
                  {tab}
                </button>
              ))}
            </div>
          </div>
          <ChartPanel activeTab={activeTab} />
        </section>

        <section>
          <div className="mb-4 flex items-center gap-3">
            <Target className="h-5 w-5 text-[#C4B5FD] print:text-purple-700" />
            <h2 className="text-2xl font-semibold">AI Recommendations</h2>
          </div>
          <div className="grid gap-4 lg:grid-cols-2">
            {recommendations.map((recommendation) => (
              <div key={recommendation.title} className="rounded-lg border border-white/10 bg-white/[0.04] p-5 print:border-slate-200 print:bg-white">
                <div className="mb-4 flex flex-wrap items-center gap-2">
                  <span className={["rounded-full px-2.5 py-1 text-xs font-semibold", recommendation.priority === "High" ? "bg-cyan-300/15 text-cyan-100 print:text-cyan-700" : "bg-[#7C3AED]/15 text-[#DDD6FE] print:text-purple-700"].join(" ")}>
                    {recommendation.priority} priority
                  </span>
                  <span className="rounded-full border border-white/10 px-2.5 py-1 text-xs text-slate-300 print:border-slate-200 print:text-slate-600">
                    {recommendation.effort} effort
                  </span>
                </div>
                <h3 className="text-lg font-semibold text-white print:text-slate-950">{recommendation.title}</h3>
                <p className="mt-3 text-sm font-medium text-cyan-100 print:text-cyan-700">{recommendation.impact}</p>
                <p className="mt-3 text-sm leading-6 text-slate-300 print:text-slate-700">{recommendation.reasoning}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]">
          <div className="rounded-lg border border-white/10 bg-white/[0.04] p-5 print:border-slate-200 print:bg-white">
            <div className="mb-4 flex items-center gap-3">
              <ShieldAlert className="h-5 w-5 text-cyan-200 print:text-cyan-700" />
              <h2 className="text-2xl font-semibold">Risk Center</h2>
            </div>
            <div className="mb-4 flex flex-wrap gap-2 print:hidden">
              {risks.map((risk) => (
                <button
                  key={risk.type}
                  type="button"
                  onClick={() => setSelectedRisk(risk.type)}
                  className={[
                    "rounded-full border px-3 py-1.5 text-xs font-medium",
                    selectedRisk === risk.type ? "border-[#A78BFA]/40 bg-[#7C3AED]/15 text-[#DDD6FE]" : "border-white/10 text-slate-300",
                  ].join(" ")}
                >
                  {risk.type}
                </button>
              ))}
            </div>
            <div className="rounded-lg border border-white/10 bg-slate-950/45 p-4 print:border-slate-200 print:bg-slate-50">
              <p className="text-sm text-slate-400 print:text-slate-600">{selectedRiskDetail.type} risk</p>
              <p className="mt-2 text-2xl font-semibold text-white print:text-slate-950">{selectedRiskDetail.status}</p>
              <p className="mt-3 text-sm leading-6 text-slate-300 print:text-slate-700">{selectedRiskDetail.detail}</p>
            </div>
            <div className="mt-4 space-y-3">
              {risks.map((risk) => (
                <div key={risk.type} className="flex items-center justify-between gap-3 rounded-lg border border-white/10 px-3 py-2 text-sm print:border-slate-200">
                  <span className="text-slate-300 print:text-slate-700">{risk.type}</span>
                  <span className="font-medium text-white print:text-slate-950">{risk.status}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="rounded-lg border border-white/10 bg-white/[0.04] p-5 print:border-slate-200 print:bg-white">
            <div className="mb-4 flex items-center gap-3">
              <CircleDollarSign className="h-5 w-5 text-[#C4B5FD] print:text-purple-700" />
              <h2 className="text-2xl font-semibold">Opportunity Center</h2>
            </div>
            <div className="grid gap-3 sm:grid-cols-2">
              {opportunities.map((opportunity) => (
                <div key={opportunity.title} className="rounded-lg border border-white/10 bg-slate-950/45 p-4 print:border-slate-200 print:bg-slate-50">
                  <p className="text-sm text-slate-400 print:text-slate-600">{opportunity.title}</p>
                  <p className="mt-2 text-2xl font-semibold text-white print:text-slate-950">{opportunity.value}</p>
                  <p className="mt-2 text-sm leading-6 text-slate-300 print:text-slate-700">{opportunity.detail}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
          <div className="rounded-lg border border-cyan-300/20 bg-gradient-to-br from-cyan-300/10 via-white/[0.04] to-[#7C3AED]/15 p-6 print:border-slate-200 print:bg-white">
            <div className="mb-4 flex items-center gap-3">
              <Brain className="h-5 w-5 text-cyan-100 print:text-cyan-700" />
              <h2 className="text-2xl font-semibold">AI Executive Conclusion</h2>
            </div>
            <p className="text-base leading-8 text-slate-200 print:text-slate-700">
              Northstar Commerce Group is in a healthy growth position with strong demand signals and credible near-term upside. Leadership should prioritize premium bundle expansion, wholesale margin discipline, and inventory rebalancing. These actions protect profit quality while converting the strongest regional and customer signals into measurable growth. The business is attractive for operators and investors because the highest-impact improvements are specific, near-term, and achievable without a major operating model change.
            </p>
          </div>

          <div className="rounded-lg border border-white/10 bg-white/[0.04] p-5 print:border-slate-200 print:bg-white">
            <div className="mb-4 flex items-center gap-3">
              <Download className="h-5 w-5 text-[#C4B5FD] print:text-purple-700" />
              <h2 className="text-2xl font-semibold">Export Area</h2>
            </div>
            <div className="grid gap-2">
              {[
                ["PDF Report", FileText],
                ["Excel", FileSpreadsheet],
                ["PowerPoint", Presentation],
                ["Share Link", LinkIcon],
                ["Print", Printer],
              ].map(([label, Icon]) => {
                const ExportIcon = Icon as typeof FileText
                return (
                  <button key={label as string} type="button" className="flex items-center justify-between rounded-lg border border-white/10 bg-slate-950/45 px-4 py-3 text-left text-sm font-medium text-slate-100 transition-colors hover:border-cyan-300/30 hover:bg-cyan-300/10 print:border-slate-200 print:bg-white print:text-slate-800">
                    <span className="flex items-center gap-3">
                      <ExportIcon className="h-4 w-4 text-cyan-200 print:text-cyan-700" />
                      {label as string}
                    </span>
                    <ArrowUpRight className="h-4 w-4 text-slate-500" />
                  </button>
                )
              })}
            </div>
          </div>
        </section>

        <section className="flex flex-col items-center justify-between gap-4 rounded-lg border border-white/10 bg-white/[0.04] p-5 text-center sm:flex-row sm:text-left print:hidden">
          <div>
            <h2 className="text-xl font-semibold">Want this report for your own business?</h2>
            <p className="mt-1 text-sm text-slate-400">Upload a spreadsheet and let UseClevr generate the next version from your data.</p>
          </div>
          <a href="/signup">
            <Button className="gap-2 rounded-full bg-cyan-300 px-6 text-slate-950 hover:bg-cyan-200">
              Analyze your data
              <TrendingUp className="h-4 w-4" />
            </Button>
          </a>
        </section>
      </main>
    </div>
  )
}
