import assert from "node:assert/strict";

import * as XLSX from "xlsx";

import {
  DatasetAnalysisPipeline,
  UniversalDatasetStructureScanner,
  buildDatasetStructureProfile,
  createPipelineContext,
  type DatasetStructureProfile,
} from "../../src/lib/data/edie";

function assertColumnType(profile: DatasetStructureProfile, columnName: string, expectedType: string) {
  const column = profile.columns.find((candidate) => candidate.name === columnName);

  assert.ok(column, `Expected column profile for ${columnName}`);
  assert.equal(column.detectedDataType.value, expectedType);
  assert.ok(column.detectedDataType.confidence >= 0.5, `${columnName} confidence should be usable`);
}

function buildCsvProfile() {
  const rawText = [
    "Company XYZ",
    "Sales Report",
    "January 2026",
    "SKU,Sales,Quantity,Email,Active,Launch Date,Metadata",
    "A-1,\"$1,200.50\",3,buyer@example.com,true,2026-01-05,\"{\"\"channel\"\":\"\"retail\"\"}\"",
    "A-2,\"$900.00\",5,owner@example.com,false,2026-01-06,\"{\"\"channel\"\":\"\"online\"\"}\"",
    "A-2,\"$900.00\",5,owner@example.com,false,2026-01-06,\"{\"\"channel\"\":\"\"online\"\"}\"",
    "Total,\"$3,000.50\",13,,,,",
    "Notes,Generated by export,,,,,",
  ].join("\n");

  return buildDatasetStructureProfile(
    createPipelineContext({
      id: "csv_header_test",
      fileName: "sales.csv",
      mimeType: "text/csv",
      rawText,
      importedAt: "2026-07-29T00:00:00.000Z",
    }),
  );
}

function buildSemicolonProfile() {
  const rawText = [
    "Region;Amount;Margin %",
    "North;1.234,50;12,5%",
    "South;2.100,00;8,1%",
  ].join("\n");

  return buildDatasetStructureProfile(
    createPipelineContext({
      id: "semicolon_test",
      fileName: "regional.csv",
      rawText,
    }),
  );
}

function buildDuplicateHeaderProfile() {
  const rawText = ["SKU,Sales,Sales", "A-1,10,12", "A-2,20,25"].join("\n");

  return buildDatasetStructureProfile(
    createPipelineContext({
      id: "duplicate_header_test",
      fileName: "duplicates.csv",
      rawText,
    }),
  );
}

function buildSparseProfile() {
  const rows = ["Name,Value"];

  for (let index = 0; index < 12; index += 1) {
    rows.push(index % 3 === 0 ? `Item ${index},${index}` : ",");
  }

  return buildDatasetStructureProfile(
    createPipelineContext({
      id: "sparse_test",
      fileName: "sparse.csv",
      rawText: rows.join("\n"),
    }),
  );
}

function buildLargeProfile() {
  const rows = ["id,value"];

  for (let index = 0; index < 12050; index += 1) {
    rows.push(`${index},${index * 2}`);
  }

  return buildDatasetStructureProfile(
    createPipelineContext({
      id: "large_csv_test",
      fileName: "large.csv",
      rawText: rows.join("\n"),
    }),
  );
}

function buildBrokenEncodingProfile() {
  return buildDatasetStructureProfile(
    createPipelineContext({
      id: "encoding_test",
      fileName: "broken.csv",
      rawText: "Name,Value\nBad�Name,10",
    }),
  );
}

function buildExcelProfile() {
  const workbook = XLSX.utils.book_new();
  const primary = XLSX.utils.aoa_to_sheet([
    ["Company XYZ"],
    ["Inventory Report"],
    ["Generated", "UTC+01:00"],
    ["SKU", "Count", "Price", "Updated At", "Website", "Record ID", "Formula"],
    ["SKU-1", 10, "$12.50", "2026-01-01 10:30", "https://example.com/a", "550e8400-e29b-41d4-a716-446655440000", 125],
    ["SKU-2", 5, "$9.25", "2026-01-02 11:00", "https://example.com/b", "550e8400-e29b-41d4-a716-446655440001", 46.25],
    ["Subtotal", 15, "$21.75", "", "", "", 171.25],
  ]);
  primary["!merges"] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: 2 } }];
  primary["!rows"] = [{ hidden: true }];
  primary["!cols"] = [{}, {}, { hidden: true }];
  primary.G5 = { t: "n", f: "B5*C5", v: 125 };
  primary.A4.c = [{ a: "qa", t: "Header comment" }];

  const sparse = XLSX.utils.aoa_to_sheet([
    ["Metric", "Value", "Owner"],
    ["A", "", ""],
    ["", "", ""],
    ["B", 2, ""],
  ]);

  XLSX.utils.book_append_sheet(workbook, primary, "Inventory");
  XLSX.utils.book_append_sheet(workbook, sparse, "Sparse");

  const rawBuffer = XLSX.write(workbook, { type: "buffer", bookType: "xlsx", compression: true }) as Buffer;

  return buildDatasetStructureProfile(
    createPipelineContext({
      id: "excel_test",
      fileName: "inventory.xlsx",
      mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      rawBuffer,
      fileSize: rawBuffer.byteLength,
    }),
  );
}

async function testCsvStructure() {
  const profile = buildCsvProfile();

  assert.equal(profile.version, "edie.structure.v1");
  assert.equal(profile.metadata.source, "csv");
  assert.equal(profile.metadata.encoding.value, "utf-8");
  assert.equal(profile.worksheets.length, 1);
  assert.equal(profile.worksheets[0].region.headerRow.value, 4);
  assert.equal(profile.worksheets[0].region.firstDataRow.value, 5);
  assert.deepEqual(profile.worksheets[0].region.footerRows.value, [8, 9]);
  assertColumnType(profile, "SKU", "Text");
  assertColumnType(profile, "Sales", "Currency");
  assertColumnType(profile, "Quantity", "Integer");
  assertColumnType(profile, "Email", "Email");
  assertColumnType(profile, "Active", "Boolean");
  assertColumnType(profile, "Launch Date", "Date");
  assertColumnType(profile, "Metadata", "JSON");
  assert.equal(profile.health.duplicateRows, 1);
  assert.ok(profile.fingerprint.length >= 32);
  assert.ok(profile.metadata.fileHash.length >= 32);
  assert.ok(profile.detectionLog.some((entry) => entry.step === "delimiter" && entry.status === "finished"));
}

async function testDelimitedAndEncodingVariants() {
  const semicolon = buildSemicolonProfile();

  assert.equal(semicolon.metadata.source, "csv");
  assert.equal(semicolon.metadata.encoding.value, "utf-8");
  assert.equal(semicolon.worksheets[0].region.headerRow.value, 1);
  assert.equal(semicolon.types.Amount.value, "Decimal");
  assert.equal(semicolon.types["Margin %"].value, "Percentage");

  const broken = buildBrokenEncodingProfile();
  assert.equal(broken.health.invalidEncoding, true);
  assert.ok(broken.errors.includes("Invalid or unsupported text encoding detected."));
}

async function testDuplicateHeadersAndSparseFiles() {
  const duplicate = buildDuplicateHeaderProfile();

  assert.deepEqual(duplicate.worksheets[0].duplicateColumns, ["Sales"]);
  assert.ok(duplicate.health.duplicateColumns.includes("Sales"));
  assert.ok(duplicate.health.recommendations.includes("Rename duplicate columns before downstream analysis."));

  const sparse = buildSparseProfile();
  assert.equal(sparse.health.sparseData, true);
  assert.ok(sparse.worksheets[0].sparseRegions.length > 0 || sparse.worksheets[0].dataDensity < 0.4);
}

async function testLargeCsvProfile() {
  const profile = buildLargeProfile();

  assert.equal(profile.metadata.rows, 12051);
  assert.equal(profile.columns.length, 2);
  assertColumnType(profile, "id", "Integer");
  assertColumnType(profile, "value", "Integer");
  assert.ok(profile.worksheets[0].columns[0].sampleValues.length <= 5);
}

async function testExcelStructure() {
  const profile = buildExcelProfile();
  const inventory = profile.worksheets.find((worksheet) => worksheet.name === "Inventory");
  const sparse = profile.worksheets.find((worksheet) => worksheet.name === "Sparse");

  assert.equal(profile.metadata.source, "excel");
  assert.equal(profile.worksheets.length, 2);
  assert.ok(inventory);
  assert.ok(sparse);
  assert.equal(inventory.region.headerRow.value, 4);
  assert.equal(inventory.region.firstDataRow.value, 5);
  assert.equal(inventory.mergedCells.length, 1);
  assert.deepEqual(inventory.hiddenRows, [1]);
  assert.deepEqual(inventory.hiddenColumns, [3]);
  assert.ok(inventory.comments.some((comment) => comment.text === "Header comment"));
  assert.ok(inventory.formulas.some((formula) => formula.formula === "B5*C5"));
  assert.equal(inventory.columns.find((column) => column.name === "Updated At")?.detectedDataType.value, "DateTime");
  assert.equal(inventory.columns.find((column) => column.name === "Website")?.detectedDataType.value, "URL");
  assert.equal(inventory.columns.find((column) => column.name === "Record ID")?.detectedDataType.value, "UUID");
  assert.equal(sparse.healthScore < inventory.healthScore, true);
  assert.ok(profile.metadata.fingerprint === profile.fingerprint);
}

async function testPipelineIntegration() {
  const scanner = new UniversalDatasetStructureScanner();
  const pipeline = new DatasetAnalysisPipeline({
    pipelineId: "edie_structure_pipeline_test",
    context: createPipelineContext({
      id: "pipeline_structure_test",
      fileName: "pipeline.csv",
      rawText: "Name,Value\nA,1\nB,2",
    }),
    scanners: [scanner],
  });
  const result = await pipeline.run();
  const structureResult = result.results.find((candidate) => candidate.scannerId === scanner.id());

  assert.ok(structureResult);
  assert.equal(structureResult.status, "completed");
  assert.equal(result.context.schema.structureProfile !== undefined, true);
  assert.equal(result.report.executedScanners[0].scannerId, scanner.id());
  assert.ok(result.report.logs.some((event) => event.event === "scanner.finished"));
}

async function main() {
  await testCsvStructure();
  await testDelimitedAndEncodingVariants();
  await testDuplicateHeadersAndSparseFiles();
  await testLargeCsvProfile();
  await testExcelStructure();
  await testPipelineIntegration();

  process.stdout.write("EDIE universal dataset structure scanner tests passed.\n");
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.stack || error.message : String(error);
  process.stderr.write(`${message}\n`);
  process.exit(1);
});
