[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["corepack enable && corepack prepare pnpm@10 --activate && pnpm install --no-frozen-lockfile --prod --no-optional --config.dangerouslyAllowAllBuilds=true"]

[phases.build]
cmds = ["if [ -d next-build ] && [ ! -d .next ]; then cp -a next-build .next; fi"]