import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import * as XLSX from "xlsx";
import {
  AccountancyUploadError,
  parseAccountancyUploadBuffer,
  validateAccountancyUpload,
  type AccountancyUploadMeta,
  type AccountancyUploadType,
} from "../../src/lib/accountancy/upload-processing";
import { categorizePrebookkeepingRows } from "../../src/lib/accountancy/prebookkeeping-categorization";

const baseMeta = (uploadType: AccountancyUploadType, fileName: string, mimeType: string): AccountancyUploadMeta => ({
  fileName,
  mimeType,
  size: 100,
  uploadType,
  datasetType: "prebookkeeping",
});

async function run() {
  await testCommaCsv();
  await testSemicolonCsv();
  await testExcel();
  await testMultiSheetExcel();
  await testExcelRejectsNonTabularFirstSheet();
  await testExcelMergedFormattedHeaderRows();
  await testSpreadsheetExportVariants();
  await testExcelNoValidSheetExplainsRejectedSheets();
  await testTextPdfInvoice();
  await testScannedPdf();
  await testImageReceipts();
  await testCsvBankExport();
  await testXlsxBankExport();
  await testOfxBankExport();
  testPrebookkeepingCategorization();
  testTwoHundredRowLedgerCategorization();
  testUnsupportedFiles();
  testUiWiring();
  testApiRouteWiring();
  console.log("Accountancy upload system regression tests passed.");
}

async function testCommaCsv() {
  const parsed = await parseAccountancyUploadBuffer(
    Buffer.from("date,description,amount\n2026-01-01,Software,12.50\n"),
    baseMeta("csv", "ledger.csv", "text/csv"),
  );
  assert.equal(parsed.route, "accountancy_csv_parser");
  assert.deepEqual(parsed.columns, ["date", "description", "amount"]);
  assert.equal(parsed.rowCount, 1);
}

async function testSemicolonCsv() {
  const parsed = await parseAccountancyUploadBuffer(
    Buffer.from("\uFEFFdate;description;amount\r\n2026-01-01;Office;12,50\r\n"),
    baseMeta("csv", "ledger.csv", "application/vnd.ms-excel"),
  );
  assert.equal(parsed.route, "accountancy_csv_parser");
  assert.deepEqual(parsed.columns, ["date", "description", "amount"]);
  assert.match(parsed.warnings.join(" "), /Detected ; delimiter/);
}

async function testExcel() {
  const parsed = await parseAccountancyUploadBuffer(
    workbookBuffer([["date", "description", "amount"], ["2026-01-01", "Software", 12.5]]),
    baseMeta("excel", "ledger.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
  );
  assert.equal(parsed.route, "accountancy_excel_workbook_parser");
  assert.equal(parsed.selectedSheet, "Sheet1");
  assert.equal(parsed.rowCount, 1);
  assert.deepEqual(parsed.columns, ["date", "description", "amount"]);
}

async function testMultiSheetExcel() {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet([["Notes"], ["empty"]]), "Notes");
  XLSX.utils.book_append_sheet(
    workbook,
    XLSX.utils.aoa_to_sheet([
      ["Bank Export"],
      ["Generated"],
      ["date", "description", "amount"],
      ["2026-01-01", "Deposit", 100],
      ["2026-01-02", "Fee", -5],
    ]),
    "Transactions",
  );
  const parsed = await parseAccountancyUploadBuffer(
    XLSX.write(workbook, { type: "buffer", bookType: "xlsx" }) as Buffer,
    baseMeta("excel", "multi.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
  );
  assert.equal(parsed.selectedSheet, "Transactions");
  assert.equal(parsed.rowCount, 2);
  assert.deepEqual(parsed.columns, ["date", "description", "amount"]);
}

async function testExcelRejectsNonTabularFirstSheet() {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(
    workbook,
    XLSX.utils.aoa_to_sheet([
      ["Accounting export"],
      ["Generated by finance"],
      ["No tabular data on this sheet"],
    ]),
    "Read me",
  );
  XLSX.utils.book_append_sheet(
    workbook,
    XLSX.utils.aoa_to_sheet([
      ["Client", "Invoice", "Amount"],
      ["ACME", "INV-1", 125],
      ["Beta", "INV-2", 230],
    ]),
    "Generic table",
  );

  const parsed = await parseAccountancyUploadBuffer(
    XLSX.write(workbook, { type: "buffer", bookType: "xlsx" }) as Buffer,
    baseMeta("excel", "generic-table.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
  );

  assert.equal(parsed.selectedSheet, "Generic table");
  assert.deepEqual(parsed.columns, ["Client", "Invoice", "Amount"]);
  assert.match(parsed.warnings.join(" "), /Rejected worksheet "Read me"/);
}

async function testExcelMergedFormattedHeaderRows() {
  const worksheet = XLSX.utils.aoa_to_sheet([
    ["Company XYZ", "", ""],
    ["Sales Report", "", ""],
    ["Customer", "Invoice", "Amount"],
    ["ACME", "INV-1", 125],
  ]);
  worksheet["!merges"] = [
    { s: { r: 0, c: 0 }, e: { r: 0, c: 2 } },
    { s: { r: 1, c: 0 }, e: { r: 1, c: 2 } },
  ];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Formatted");

  const parsed = await parseAccountancyUploadBuffer(
    XLSX.write(workbook, { type: "buffer", bookType: "xlsx" }) as Buffer,
    baseMeta("excel", "formatted.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
  );

  assert.equal(parsed.selectedSheet, "Formatted");
  assert.deepEqual(parsed.columns, ["Customer", "Invoice", "Amount"]);
  assert.equal(parsed.rowCount, 1);
}

async function testSpreadsheetExportVariants() {
  const variants = [
    ["excel-export.xlsx", "Excel Export"],
    ["google-sheets-export.xlsx", "Google Sheets Export"],
    ["libreoffice-export.xlsx", "LibreOffice Export"],
  ] as const;

  for (const [fileName, sheetName] of variants) {
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(
      workbook,
      XLSX.utils.aoa_to_sheet([
        ["Account", "Reference", "Value"],
        ["Sales", "REF-1", 100],
      ]),
      sheetName,
    );
    const parsed = await parseAccountancyUploadBuffer(
      XLSX.write(workbook, { type: "buffer", bookType: "xlsx" }) as Buffer,
      baseMeta("excel", fileName, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
    );

    assert.equal(parsed.selectedSheet, sheetName);
    assert.deepEqual(parsed.columns, ["Account", "Reference", "Value"]);
  }
}

async function testExcelNoValidSheetExplainsRejectedSheets() {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet([[]]), "Empty");
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet([["Notes"], ["Generated only"]]), "Notes");

  await assert.rejects(
    () =>
      parseAccountancyUploadBuffer(
        XLSX.write(workbook, { type: "buffer", bookType: "xlsx" }) as Buffer,
        baseMeta("excel", "notes-only.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
      ),
    (error) =>
      error instanceof AccountancyUploadError &&
      error.code === "EXCEL_NO_DATA_SHEET" &&
      error.message.includes("Empty: Sheet is empty.") &&
      error.message.includes("Notes: No generic tabular region"),
  );
}

async function testTextPdfInvoice() {
  const pdf = Buffer.from(
    "%PDF-1.4\n(Supplier: ACME Ltd)\n(Invoice Number: INV-1001)\n(Date: 2026-01-31)\n(Currency: EUR)\n(Subtotal: 100.00)\n(VAT: 21.00)\n(Total: 121.00)\n%%EOF",
  );
  const parsed = await parseAccountancyUploadBuffer(pdf, baseMeta("pdf", "invoice.pdf", "application/pdf"));
  assert.equal(parsed.route, "accountancy_pdf_document_processor");
  assert.equal(parsed.documentTextStatus, "embedded_text");
  assert.ok(parsed.extractedData.some((field) => field.field === "invoiceNumber" && field.value === "INV-1001"));
  assert.ok(parsed.extractedData.some((field) => field.field === "total" && field.value === "121.00"));
}

async function testScannedPdf() {
  const parsed = await parseAccountancyUploadBuffer(Buffer.from("%PDF-1.4\n%%EOF"), baseMeta("pdf", "scan.pdf", "application/pdf"));
  assert.equal(parsed.route, "receipt_document_scanner");
  assert.equal(parsed.documentTextStatus, "scanner_required");
}

async function testImageReceipts() {
  const jpg = await parseAccountancyUploadBuffer(Buffer.from([255, 216, 255, 217]), baseMeta("receipt", "receipt.jpg", "image/jpeg"));
  assert.equal(jpg.route, "receipt_invoice_document_scanner");
  assert.equal(jpg.documentTextStatus, "image_scanner");

  const png = await parseAccountancyUploadBuffer(Buffer.from([137, 80, 78, 71]), baseMeta("receipt", "receipt.png", "image/png"));
  assert.equal(png.route, "receipt_invoice_document_scanner");
  assert.equal(png.documentTextStatus, "image_scanner");
}

async function testCsvBankExport() {
  const parsed = await parseAccountancyUploadBuffer(
    Buffer.from("date,description,debit,credit,currency,balance,reference\n2026-01-01,Fee,5,,EUR,95,ABC\n2026-01-02,Sale,,25,EUR,120,DEF\n"),
    baseMeta("bank", "bank.csv", "text/csv"),
  );
  assert.equal(parsed.route, "bank_transaction_parser");
  assert.equal(parsed.rows[0]?.normalizedAmount, -5);
  assert.equal(parsed.rows[1]?.normalizedAmount, 25);
}

async function testXlsxBankExport() {
  const parsed = await parseAccountancyUploadBuffer(
    workbookBuffer([["date", "description", "amount"], ["2026-01-01", "Deposit", 250]]),
    baseMeta("bank", "bank.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
  );
  assert.equal(parsed.route, "bank_transaction_parser");
  assert.equal(parsed.rows[0]?.normalizedAmount, 250);
}

async function testOfxBankExport() {
  const ofx = Buffer.from("<OFX><BANKTRANLIST><STMTTRN><DTPOSTED>20260101<TRNAMT>-9.99<FITID>1<NAME>Bank fee</BANKTRANLIST></OFX>");
  const parsed = await parseAccountancyUploadBuffer(ofx, baseMeta("bank", "bank.ofx", "application/octet-stream"));
  assert.equal(parsed.route, "bank_transaction_parser");
  assert.equal(parsed.rows[0]?.normalizedAmount, -9.99);
}

function testUnsupportedFiles() {
  const unsupported: Array<[AccountancyUploadType, string, string]> = [
    ["csv", "invoice.pdf", "application/pdf"],
    ["excel", "ledger.csv", "text/csv"],
    ["pdf", "receipt.jpg", "image/jpeg"],
    ["receipt", "ledger.csv", "text/csv"],
    ["bank", "receipt.jpg", "image/jpeg"],
  ];

  for (const [uploadType, fileName, mimeType] of unsupported) {
    assert.throws(
      () => validateAccountancyUpload(baseMeta(uploadType, fileName, mimeType)),
      (error) => error instanceof AccountancyUploadError && error.stage === "validation",
    );
  }
}

function testUiWiring() {
  const source = readFileSync("src/components/accountancy/accountancy-upload.tsx", "utf8");
  assert.ok(source.includes('fetch("/api/accountancy/upload"'), "Accountancy UI uses dedicated route");
  assert.ok(source.includes('formData.append("uploadType", selectedType)'), "selected upload type is submitted");
  assert.ok(source.includes("resetSelectedFileState"), "tab switching clears selected file and errors");
  assert.ok(source.includes("fileInputRef.current.value = \"\""), "file input is cleared on tab switch");
  assert.ok(!source.includes("simulateExtraction"), "mock extraction is removed");
  assert.ok(!source.includes("Math.random() * 1000"), "random mock transactions are removed");
}

function testApiRouteWiring() {
  const route = readFileSync("src/app/api/accountancy/upload/route.ts", "utf8");
  const processor = readFileSync("src/lib/accountancy/upload-processing.ts", "utf8");
  const prebookkeepingPage = readFileSync("src/app/(auth)/app/prebookkeeping/page.tsx", "utf8");
  const reviewRoute = readFileSync("src/app/api/prebookkeeping/review/route.ts", "utf8");
  const exportRoute = readFileSync("src/app/api/prebookkeeping/export/route.ts", "utf8");
  const reviewWorkspace = readFileSync("src/components/accountancy/prebookkeeping-review-workspace.tsx", "utf8");
  assert.ok(route.includes("processAccountancyUpload"), "API route uses Accountancy processor");
  assert.ok(route.includes("stage"), "API route returns staged errors");
  assert.ok(processor.includes("eq(datasets.checksum, checksum)"), "processor reuses duplicate datasets by checksum");
  assert.ok(processor.includes("categorizePrebookkeepingRows(parsed.rows, learningRules)"), "Pre-bookkeeping uploads start categorization automatically");
  assert.ok(prebookkeepingPage.includes("Ready for review"), "Pre-bookkeeping page shows ready-for-review status");
  assert.ok(prebookkeepingPage.includes("StartCategorizationButton"), "Pre-bookkeeping page exposes a categorization action for legacy datasets");
  assert.ok(reviewRoute.includes("prebookkeepingLearningRules"), "manual category edits persist learning rules");
  assert.ok(reviewRoute.includes("prebookkeepingAuditEvents"), "review actions write audit events");
  assert.ok(exportRoute.includes("reviewedRows"), "exports use reviewed transactions only");
  assert.ok(reviewWorkspace.includes("AI Review Summary"), "review workspace shows AI review summary");
  assert.ok(reviewWorkspace.includes("Missing VAT"), "review workspace includes review queue filters");
  assert.ok(reviewWorkspace.includes("Confidence"), "review workspace displays prediction confidence");
  assert.ok(!route.includes("reserveCredits") && !processor.includes("reserveCredits"), "failed uploads do not reserve credits");
  assert.ok(!route.includes("finalizeCredits") && !processor.includes("finalizeCredits"), "Accountancy upload route does not finalize credits");
}

function testPrebookkeepingCategorization() {
  const summary = categorizePrebookkeepingRows([
    { date: "2026-01-01", description: "Customer payment INV-1", credit: 100, currency: "EUR", vat: 21, reference: "INV-1" },
    { date: "2026-01-02", description: "Monthly rent", debit: 40, currency: "EUR", vat: 8, reference: "BILL-1" },
    { date: "2026-01-03", description: "Average Gross Salary", debit: 60, currency: "EUR", reference: "PAY-1" },
    { date: "2026-01-04", description: "Bank fee", debit: 2, currency: "EUR", reference: "FEE-1" },
    { date: "2026-01-05", description: "VAT payment", debit: 10, currency: "EUR", reference: "TAX-1" },
    { date: "2026-01-06", description: "Internal transfer", amount: 0, currency: "EUR", reference: "TR-1" },
    { date: "2026-01-07", description: "", currency: "EUR" },
  ]);

  assert.equal(summary.status, "ready_for_review");
  assert.equal(summary.categoryCounts.revenue, 1);
  assert.equal(summary.categoryCounts.fixed_costs, 1);
  assert.equal(summary.categoryCounts.payroll, 1);
  assert.equal(summary.categoryCounts.bank_fees, 1);
  assert.equal(summary.categoryCounts.taxes, 1);
  assert.equal(summary.categoryCounts.transfers, 1);
  assert.equal(summary.categoryCounts.uncategorized, 1);
  assert.equal(summary.incomeTotal, 100);
  assert.equal(summary.expenseTotal, 112);
  assert.equal(summary.vatTaxSummary.total, 29);
}

function testTwoHundredRowLedgerCategorization() {
  const rows = Array.from({ length: 200 }, (_, index) => {
    const rowNumber = index + 1;
    const type = rowNumber % 8;
    return {
      transaction_date: `2026-01-${String((rowNumber % 28) + 1).padStart(2, "0")}`,
      description:
        type === 0
          ? "Customer payment"
          : type === 1
            ? "Office supplies"
            : type === 2
              ? "Monthly rent"
              : type === 3
                ? "Average Gross Salary"
                : type === 4
                  ? "VAT payment"
                  : type === 5
                    ? "Bank fee"
                    : type === 6
                      ? "Internal transfer"
                      : "",
      supplier_customer: type === 0 ? "Customer" : "Supplier",
      debit: type === 0 ? "" : 10 + rowNumber,
      credit: type === 0 ? 25 + rowNumber : "",
      amount: "",
      currency: "EUR",
      vat_tax: type === 1 || type === 2 ? 2 : "",
      category: "",
      invoice_reference: `REF-${rowNumber}`,
      cost_center: "HQ",
      notes: "",
    };
  });

  const summary = categorizePrebookkeepingRows(rows);
  assert.equal(summary.rowCount, 200);
  assert.equal(Object.keys(rows[0] || {}).length, 12);
  assert.equal(summary.transactions.length, 200);
  assert.ok(summary.categorizedCount > summary.uncategorizedCount);
  assert.ok(summary.incomeTotal > 0);
  assert.ok(summary.expenseTotal > 0);
}

function workbookBuffer(rows: unknown[][]) {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet(rows), "Sheet1");
  return XLSX.write(workbook, { type: "buffer", bookType: "xlsx" }) as Buffer;
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
